<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/18 10:51:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bee-project',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
